# Generated by Django 6.0.7 on 2026-08-10 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ImageEmbedding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('embedding_vector', models.BinaryField()),
                ('embedding_dimension', models.IntegerField(default=1024)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Image Embedding',
                'verbose_name_plural': 'Image Embeddings',
            },
        ),
        migrations.CreateModel(
            name='RecommendedProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recommendation_type', models.CharField(choices=[('visual_similarity', 'Visual Similarity'), ('collaborative', 'Collaborative Filtering'), ('content_based', 'Content-Based')], max_length=20)),
                ('confidence_score', models.FloatField(default=0.0)),
                ('reason', models.TextField(blank=True, null=True)),
                ('clicked', models.BooleanField(default=False)),
                ('purchased', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Recommended Product',
                'verbose_name_plural': 'Recommended Products',
                'ordering': ['-confidence_score'],
            },
        ),
        migrations.CreateModel(
            name='VisionSearchQuery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('query_image', models.ImageField(upload_to='vision_queries/')),
                ('results_count', models.IntegerField(default=0)),
                ('execution_time', models.FloatField(help_text='Time in seconds')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Vision Search Query',
                'verbose_name_plural': 'Vision Search Queries',
                'ordering': ['-created_at'],
            },
        ),
    ]
